spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales_info
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  batch:
    jdbc:
      platform: postgresql
      initialize-schema: always
    job:
      enabled: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    template:
      default-topic: sales.info

sales:
  info:
    directory: /Users/pawelsiwon/Documents/git/salesinfo/src/main/resources/data