spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales_info
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  batch:
    jdbc:
      platform: postgresql
      initialize-schema: always
    job:
      enabled: false

sales:
  info:
    directory: /Users/pawelsiwon/Documents/git/salesinfo/src/main/resources/data