version: '3'

services:
  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sales_info
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"